### ISSUE TITLE
Paper Roadmap

### ISSUE THREAD

**Issue by EiffL** [EiffL/sfh-inference-hackathon#27]
We will use this issue to keep track of progress and action items for the paper.

## Data preparation
**People**: @mhuertascompany @EiffL 
 - [ ] : Adding Eagles data

## Summary Statistics regression section: 
**People**: @aghribi @crosset @Siouar (@ppfn ?)
  - [ ] :  Setting up notebook to use `tng100` dataset and produce first plots of true vs predicted t50/total mass with full SED
  - [ ] : Implementing variant of above with various inputs (subset of bands in SED), using images
  - [ ] : Implement an information criterium to compare information content

## Full history inference section: 
**People**: @16Aghnar @laurilaatu @yannick1974 
  - [ ] : Setting up clean notebook to use `tng100` dataset
  - [ ] : Generate plots of true vs predicted sfh for distinct classes of galaxies
  - [ ] : Conditioning on image+SED
  - [ ] : Infer t10/t50... from reconstructed history
